on: pull_request
jobs:
  hello:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    steps:
      - uses: szksh-lab-2/test-github-action/.github/actions/bar@test-self-repo-syntax
